name: Apartment Checker

on:
  schedule:
    # Run every hour from 6 AM to 2 AM Vancouver time (PDT)
    - cron: '0 13-23 * * *'
    - cron: '0 0-8 * * *'
  workflow_dispatch:

jobs:
  check-apartments:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '18'

    - name: Install dependencies
      run: npm install

    - name: Run Apartment Checker
      env:
        RESEND_API_KEY: ${{ secrets.RESEND_API_KEY }}
        EMAIL_TO: ${{ secrets.EMAIL_TO }}
      run: node checkApartments.js

    - name: Commit and Push updated listings.json
      run: |
        git config --global user.name "github-actions"
        git config --global user.email "actions@github.com"
        git add listings.json
        git commit -m "Update listings.json with new listings"
        git push
      continue-on-error: true  